<?php
/**
 * Created by PhpStorm.
 * User: Paul Rybitskyi
 * Date: 11/6/17
 * Time: 2:37 AM
 */

namespace App\Database\Schemas;

abstract class Procedures {


    const INCREMENT_DICTIONARY_ENTRY_LEARNER_COUNT_PROCEDURE_NAME = 'incrementDictionaryEntryLearnerCount';
    const INCREMENT_DICTIONARY_ENTRY_LEARNER_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const DECREMENT_DICTIONARY_ENTRY_LEARNER_COUNT_PROCEDURE_NAME = 'decrementDictionaryEntryLearnerCount';
    const DECREMENT_DICTIONARY_ENTRY_LEARNER_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const INCREMENT_DICTIONARY_ENTRY_MASTER_COUNT_PROCEDURE_NAME = 'incrementDictionaryEntryMasterCount';
    const INCREMENT_DICTIONARY_ENTRY_MASTER_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const DECREMENT_DICTIONARY_ENTRY_MASTER_COUNT_PROCEDURE_NAME = 'decrementDictionaryEntryMasterCount';
    const DECREMENT_DICTIONARY_ENTRY_MASTER_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const INCREMENT_DICTIONARY_ENTRY_LIKE_COUNT_PROCEDURE_NAME = 'incrementDictionaryEntryLikeCount';
    const INCREMENT_DICTIONARY_ENTRY_LIKE_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const DECREMENT_DICTIONARY_ENTRY_LIKE_COUNT_PROCEDURE_NAME = 'decrementDictionaryEntryLikeCount';
    const DECREMENT_DICTIONARY_ENTRY_LIKE_COUNT_PROCEDURE_DICTIONARY_ENTRY_ID_PARAMETER_NAME = 'dictionary_entry_id';

    const INCREMENT_USER_FRIEND_COUNT_PROCEDURE_NAME = 'incrementUserFriendCount';
    const INCREMENT_USER_FRIEND_COUNT_PROCEDURE_USER_ID_PARAMETER_NAME = 'user_id';

    const DECREMENT_USER_FRIEND_COUNT_PROCEDURE_NAME = 'decrementUserFriendCount';
    const DECREMENT_USER_FRIEND_COUNT_PROCEDURE_USER_ID_PARAMETER_NAME = 'user_id';

    const INCREMENT_USER_FOLLOWER_COUNT_PROCEDURE_NAME = 'incrementUserFollowerCount';
    const INCREMENT_USER_FOLLOWER_COUNT_PROCEDURE_USER_ID_PARAMETER_NAME = 'user_id';

    const DECREMENT_USER_FOLLOWER_COUNT_PROCEDURE_NAME = 'decrementUserFollowerCount';
    const DECREMENT_USER_FOLLOWER_COUNT_PROCEDURE_USER_ID_PARAMETER_NAME = 'user_id';


}